### ISSUE TITLE
Configure Cognito to not send the temporary password

### ISSUE THREAD

**Issue by thombergs** [aws101/aws101#19]
Is it possible to configure Cognito so that it send a confirmation link to the user's email address?

**Comment by BjoernKW** [comment]
This was caused by this particular line in the registration code:
`.withTemporaryPassword(registration.getPassword())`

Removing this line has AWS Cognito generate a temporary password automatically on the user's behalf. This means that the password fields aren't required during registration either because the user has to set her actual persistent password with AWS Cognito anyway.
